# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-14 05:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='month',
            name='id',
        ),
        migrations.AddField(
            model_name='month',
            name='employee_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Employee'),
            preserve_default=False,
        ),
    ]
