# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-14 05:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170114_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='created_date',
        ),
    ]
