# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-14 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_employee_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='month',
            name='employee_ptr',
        ),
        migrations.AddField(
            model_name='month',
            name='employees',
            field=models.ManyToManyField(to='app.Employee'),
        ),
        migrations.AddField(
            model_name='month',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
