# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20170114_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='no_of_hours_absent',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
