# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_month_no_of_hours_absent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='month',
            name='Employee',
        ),
        migrations.AddField(
            model_name='month',
            name='Employees',
            field=models.ManyToManyField(to='app.Employee'),
        ),
    ]
