# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20170119_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('no_of_holidays', models.CharField(max_length=10)),
                ('total_advance_overhead', models.CharField(max_length=15)),
                ('no_of_hours_absent', models.CharField(max_length=10)),
                ('Employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Employee')),
            ],
        ),
        migrations.RemoveField(
            model_name='month',
            name='Employees',
        ),
        migrations.DeleteModel(
            name='Month',
        ),
    ]
