# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20170123_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
