# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20170124_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='month',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='year',
            field=models.IntegerField(blank=True),
        ),
    ]
