# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-17 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20170124_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='month',
        ),
        migrations.RemoveField(
            model_name='record',
            name='year',
        ),
        migrations.AddField(
            model_name='record',
            name='pending',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
