# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-20 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20170217_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='this_month_salary',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
